import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "@/componentes/header";
const inter = Inter({ subsets: ["latin"] });
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
      <Header/>
        {children}
        
      </body>
    </html>
  );
}
